
use_frameworks!
platform :ios, '11.0'

target 'FSEmptyDataSet_Example' do
  pod 'FSEmptyDataSet', :path => '../'
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Sheng"
  # disable bitcode.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
